Drugstore:
- DM\.DROGERIE\.SAGT\.DANKE/Unterhaching
- ROSSMANN
Fitness:
- UZR\.body\.\.\.soul\.body\.\./Munchen
- Wellhub
Groceries:
- Filiale\.19\.\.Unterhachin/Unterhaching
- EDEKA
- ALDI\.SUED/Unterhaching
Insurance:
- Envivas\ Krankenversicherung\ AG
Leisure:
- BergTierPark\.Blindham/Aying
Phone:
- klarmobil\ GmbH
- AMANDINES\.ET\.CHOCOLATS/MUENCHEN
Restaurant:
- SUPREMO\.KAFFEEROSTEREI/UNTERHACHING
- Lieferando
Shopping:
- AMAZON\ EU\ S\.A\ R\.L\.,\ NIEDERLASSUNG\ DEUTSCHLAND
- PayPal\ Europe\ S\.a\.r\.l\.\ et\ Cie\ S\.C\.A
Technology:
- Apple
- Anthropic\ Claude\ Subscription
